/*
Microduino Single digital dice
*/

//Define the segment code table in paragraph ten elements generated by the LED code generator, select the common anode.
int a[10] = {0xC0, 0xF9, 0xA4, 0xB0, 0x99, 0x92, 0x82, 0xF8, 0x80, 0x90};
void setup()
{
    DDRD = 0xFF;          //AVR define PortD's low 7 bit used to printout。0xFF=B11111111 correspending D7~D0
    pinMode(12, INPUT);    //D12 is used to pause switch
}
void loop()
{
    for(int i = 0; i < 10; i++)
    {
        //The lower section 7 of code output PortD , namely Arduino pin D0 ~ D6, so need to remove PORTD highest bit D7 of the state that, with the segment code added after the re-export.
        PORTD = a[i];
        delay(50);        //delay 50ms
        while(digitalRead(12)) {}        //If D12 pin high, in this endless loop, suspend LED running
    }
}
